### Get all expenses (no auth needed)
GET https://localhost:7091/api/Expense

### Create expense (protected)
POST https://localhost:7091/api/Expense/CreateExpense
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJteWJhY2tiYWNrdXAyMTBAZ21haWwuY29tIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6ImJhY2t1cCBteUJhY2siLCJleHAiOjE3NzQyNzY5NDksImlzcyI6IlRyYWNrQW0iLCJhdWQiOiJUcmFja0FtVXNlcnMifQ.Xyt0Wj2JA5QFmWkqht0lHmRhd4k5F6ggzxH0AKbnFkE

{
    "description": "Test expense",
    "amount": 50.00,
    "categoryId": 1
}

### Update expense (protected)
PUT https://localhost:7091/api/Expense/UpdateExpense/11
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJteWJhY2tiYWNrdXAyMTBAZ21haWwuY29tIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6ImJhY2t1cCBteUJhY2siLCJleHAiOjE3NzQyNzY5NDksImlzcyI6IlRyYWNrQW0iLCJhdWQiOiJUcmFja0FtVXNlcnMifQ.Xyt0Wj2JA5QFmWkqht0lHmRhd4k5F6ggzxH0AKbnFkE

{
    "id": 11,
    "description": "Updated test expense",
    "amount": 75.00,
    "categoryId": 1
}

### myexpense
GET https://localhost:7091/api/Expense/MyExpenses
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJteWJhY2tiYWNrdXAyMTBAZ21haWwuY29tIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6ImJhY2t1cCBteUJhY2siLCJleHAiOjE3NzQyNzY5NDksImlzcyI6IlRyYWNrQW0iLCJhdWQiOiJUcmFja0FtVXNlcnMifQ.Xyt0Wj2JA5QFmWkqht0lHmRhd4k5F6ggzxH0AKbnFkE

{
}


### Delete expense (protected)
DELETE https://localhost:7091/api/Expense/DeleteExpense/12
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJteWJhY2tiYWNrdXAyMTBAZ21haWwuY29tIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6ImJhY2t1cCBteUJhY2siLCJleHAiOjE3NzQyNzY5NDksImlzcyI6IlRyYWNrQW0iLCJhdWQiOiJUcmFja0FtVXNlcnMifQ.Xyt0Wj2JA5QFmWkqht0lHmRhd4k5F6ggzxH0AKbnFkE



###Category
GET https://localhost:7091/api/Expense/Category/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJteWJhY2tiYWNrdXAyMTBAZ21haWwuY29tIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6ImJhY2t1cCBteUJhY2siLCJleHAiOjE3NzQyNzY5NDksImlzcyI6IlRyYWNrQW0iLCJhdWQiOiJUcmFja0FtVXNlcnMifQ.Xyt0Wj2JA5QFmWkqht0lHmRhd4k5F6ggzxH0AKbnFkE


### Category all Categories
GET https://localhost:7091/api/Category


###Create Category
POST https://localhost:7091/api/Category/CreateCategory
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJteWJhY2tiYWNrdXAyMTBAZ21haWwuY29tIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6ImJhY2t1cCBteUJhY2siLCJleHAiOjE3NzQyNzY5NDksImlzcyI6IlRyYWNrQW0iLCJhdWQiOiJUcmFja0FtVXNlcnMifQ.Xyt0Wj2JA5QFmWkqht0lHmRhd4k5F6ggzxH0AKbnFkE

{
    "name": "academic",
    "Description": ""
}


###Delete Category
DELETE https://localhost:7091/api/Category/DeleteCategory/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJteWJhY2tiYWNrdXAyMTBAZ21haWwuY29tIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6ImJhY2t1cCBteUJhY2siLCJleHAiOjE3NzQyNzY5NDksImlzcyI6IlRyYWNrQW0iLCJhdWQiOiJUcmFja0FtVXNlcnMifQ.Xyt0Wj2JA5QFmWkqht0lHmRhd4k5F6ggzxH0AKbnFkE


### Update Category
PUT https://localhost:7091/api/Category/UpdateCategories/15
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJteWJhY2tiYWNrdXAyMTBAZ21haWwuY29tIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6ImJhY2t1cCBteUJhY2siLCJleHAiOjE3NzQyNzY5NDksImlzcyI6IlRyYWNrQW0iLCJhdWQiOiJUcmFja0FtVXNlcnMifQ.Xyt0Wj2JA5QFmWkqht0lHmRhd4k5F6ggzxH0AKbnFkE

{
    "Name": "Updated Category",
    "Description" : "This is an updated category"
}


###GetAll User

GET https://localhost:7091/api/User/
